/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.

 * ubs-io is licensed under the Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *      http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */

#ifndef MESSAGE_OP_H
#define MESSAGE_OP_H

#include <cstdint>

enum BioOpCode : uint16_t {
    BIO_OP_SDK_SHM_INIT = 0,
    BIO_OP_SDK_GET_NODE_INFO,
    BIO_OP_SDK_GET_NODE_INFO_BY_PT,
    BIO_OP_SDK_GET_QUOTA_INFO,
    BIO_OP_SDK_ALLOC_QUOTA,
    BIO_OP_SDK_FREE_QUOTA,
    BIO_OP_SDK_GET_NODE_VIEW,
    BIO_OP_SDK_QUERY_PT_VIEW,
    BIO_OP_SDK_PUT,
    BIO_OP_SDK_GET,
    BIO_OP_SDK_DELETE,
    BIO_OP_SDK_ADD_DISK,
    BIO_OP_SDK_STAT,
    BIO_OP_SDK_LIST,
    BIO_OP_SDK_LOAD,
    BIO_OP_SDK_CREATE_FLOW,
    BIO_OP_SDK_DESTROY_FLOW,
    BIO_OP_SDK_GET_SLICE,
    BIO_OP_SERVER_SYNC_DATA,
    BIO_OP_SERVER_GET_EVICT_OFFSET,
    BIO_OP_SDK_FREE_MEM,
    BIO_OP_SDK_NOTIFY_UPDATE,
    BIO_OP_SDK_CHECK_UPDATE_READY,
    BIO_OP_SERVER_CHECK_REMOTE_UPDATE_READY,
    BIO_OP_INTERCEPTOR_READ,
    BIO_OP_INTERCEPTOR_WRITE,
    BIO_OP_INTERCEPTOR_ALLOC_BUFF,
    BIO_OP_INTERCEPTOR_LARGE_WRITE,
    BIO_OP_INTERCEPTOR_LARGE_READ,
    BIO_OP_SDK_GET_UFS_CONFIG,
    BIO_OP_SERVER_NEGOTIATE_EVICT,
    BIO_OP_SDK_GET_CACHE_HIT,
    BIO_OP_SDK_QUERY_CACHE_RESOURCE,
    BIO_OP_SDK_GET_TRACE_POINTS,
    BIO_OP_SDK_CLEAR_WCACHE,
    BIO_OP_BUTT
};

#endif // MESSAGE_OP_H
