# configuration for matrix mem store
[mms]
## Log
mms.log.level = info

## Trace
mms.trace.switch = false

## Crc
mms.crc.switch = false

## Sequence
mms.sequence.switch = false

## Multicast
mms.multicast.switch = true

## Deployment
mms.deployment.mode = separate

## Memory
mms.mem.numa.id = 0,1
mms.mem.numa.size = 8,8
mms.mem.min_block_size = 2
mms.mem.max_block_size = 10
mms.mem.min_max_block_rate = 8:2

## Network
mms.net.rpc.ip_mask = 192.168.100.100/24
mms.net.rpc.listen_port = 7500
mms.net.multicast.listen_port = 7501
mms.net.rpc.protocol = rdma
mms.net.multicast.protocol = rdma
mms.net.rpc.connect.count = 1
mms.net.rpc.busy_polling_mode = true
mms.net.rpc.worker.groups = 1,1
mms.net.rpc.worker.groups.cpuset = 10-10,50-50
mms.net.ipc.busy_polling_mode = true
mms.net.ipc.worker.groups = 1,1
mms.net.ipc.worker.groups.cpuset = 12-12,52-52
mms.net.request.executor.thread.num = 8
mms.net.request.executor.queue.size = 1024
mms.net.publisher.worker.cpuset = 10-17
mms.net.subscriber.worker.cpuset = 18-18
mms.net.message.max_buff_size = 70
mms.net.tls.enable = true
mms.net.tls.certification.path =
mms.net.tls.ca.cert.path =
mms.net.tls.ca.crl.path =
mms.net.tls.private.key.path =
mms.net.tls.private.key.password.path =
mms.net.tls.decrypter.lib.path =
mms.net.tls.openssl.lib.path =

## Cluster manager
mms.cm.node.num = 3
mms.cm.register_timeout_sec = 10
mms.cm.zk_host = 192.168.100.100:2181
