/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2023. All rights reserved.
 */

#include "bio_cache_tp.h"

using namespace ock::bio;
using namespace ock::bio::tp;
#ifdef __aarch64__
static uint32_t MY_PID = 102;

void tp::CacheTp::Register() noexcept
{
    LVOS_TP_REG(CACHE_RECOVER_CACHE_FAIL, "cache recover cache err", CommonTp::IntValueCallback);
    LVOS_TP_REG(SLICE_OPERATOR_4_FLOW_MEMORY, "slice operator 4 params flow memory err", CommonTp::IntValueCallback);
    LVOS_TP_REG(LISTALL_REMOTE_OVER_1000, "listall remote return data over 1000", CommonTp::IntValueCallback);
    LVOS_TP_REG(LISTALL_REMOTE_RSP_OVER_LIMIT, "listall remote return data over 1000", CommonTp::IntValueCallback);
    LVOS_TP_REG(SLICE_COPY_DISK2MEMORY_OK, "slice copy disk to memory ok", CommonTp::IntValueCallback);
    LVOS_TP_REG(SLICE_COPY_MEMORY2MEMORY_ERR, "slice copy memory to memory err", CommonTp::IntValueCallback);
    LVOS_TP_REG(SLICE_OPERATOR_FLOW_MEMORY, "slice operator flow memory err", CommonTp::IntValueCallback);
    LVOS_TP_REG(SLICE_OPERATOR_2_FLOW_MEMORY, "slice operator to flow memory err", CommonTp::IntValueCallback);
    LVOS_TP_REG(CACHE_RECOVER_FM_GET_ALL_OBJECT_FAIL, "recover alloc object err", CommonTp::IntValueCallback);
    LVOS_TP_REG(WCACHE_READ_CALLBACK_FAIL, "wcache read callback err", CommonTp::IntValueCallback);
    LVOS_TP_REG(LOG_INIT_FAIL, "log init err", CommonTp::IntValueCallback);
    LVOS_TP_REG(TRACE_FILE_OPPEN_FAIL, "trace file open err", CommonTp::IntValueCallback);
    LVOS_TP_REG(EVICT_NEGOTIATE_VECTOR_EMPTY, "evict negotiate vectort is empty", CommonTp::BoolValueCallback);
    LVOS_TP_REG(EVICT_NEGOTIATE_GET_MASTERNODE, "evict negotiate get master node ok", CommonTp::IntValueCallback);
    LVOS_TP_REG(CONFIG_INIT_FAIL, "config init err", CommonTp::IntValueCallback);
    LVOS_TP_REG(DESTROY_WCACHE_FAIL, "destroy wcache err", CommonTp::BoolValueCallback);
    LVOS_TP_REG(WCACHE_DELETE_FLOWID_ERR, "wcache delete flowid err", CommonTp::IntValueCallback);
    LVOS_TP_REG(RCACHE_MANAGER_DELETE_ERR, "rcache manager delete err", CommonTp::PointerValueCallback);
    LVOS_TP_REG(NO_PROCESS_CLEAR_OLD_CACHE, "no process clear old cache", CommonTp::NoProcessCallback);
    LVOS_TP_REG(NO_PROCESS_FLUSH, "no process flush", CommonTp::NoProcessCallback);
    LVOS_TP_REG(LIST_LIST_FAIL, "list list err", CommonTp::IntValueCallback);
    LVOS_TP_REG(LIST_MALLOC_RSP_FAIL, "list malloc rsp err", CommonTp::PointerValueCallback);
    LVOS_TP_REG(PUT_ALLOC_SLICE_FAIL, "put alloc slice err", CommonTp::PointerValueCallback);
    LVOS_TP_REG(PUT_SLICELEN_ZERO_ALLOC_SLICE_FAIL, "put alloc slice err", CommonTp::PointerValueCallback);
    LVOS_TP_REG(WCACHE_FLOW_OFFSET_FAIL, "wcache flow offset failed", CommonTp::BoolValueCallback);
    LVOS_TP_REG(WCACHE_HOLD_WAIT_FAIL, "wcache hold wait err", CommonTp::IntValueCallback);
    LVOS_TP_REG(TRACE_CREATE_DIR_FAIL, "trace create dir err", CommonTp::IntValueCallback);
    LVOS_TP_REG(TRACE_PATH_REAL_FAIL, "trace path real err", CommonTp::PointerValueCallback);
    LVOS_TP_REG(UNDERFS_OPEN_DIR_FAIL, "underfs open dir err", CommonTp::PointerValueCallback);
    LVOS_TP_REG(UNDERFS_MKDIR_FAIL, "underfs make dir err", CommonTp::IntValueCallback);
    LVOS_TP_REG(QUEUE_INIT_FAIL, "queue init err", CommonTp::IntValueCallback);
    LVOS_TP_REG(EXECUTOR_THREAD_FAIL, "executor thread err", CommonTp::PointerValueCallback);
    LVOS_TP_REG(RCACHE_GC_THREAD_FAIL, "rcache gc thread err", CommonTp::PointerValueCallback);
    LVOS_TP_REG(RCACHE_EVICT_THREAD_FAIL, "rcache evict thread err", CommonTp::PointerValueCallback);
    LVOS_TP_REG(CLI_AGENT_INIT_ERR, "cli agent init err", CommonTp::IntValueCallback);
    LVOS_TP_REG(CLI_SERVER_DIAGNOSE_HANDLER_ERR, "cli server handler err", CommonTp::PointerValueCallback);
    LVOS_TP_REG(CLI_SERVER_DIAGNOSE_INIT_ERR, "cli server init err", CommonTp::IntValueCallback);
    LVOS_TP_REG(WCACHE_FLOW_DISK_FAIL, "wcache flow disk err", CommonTp::IntValueCallback);
    LVOS_TP_REG(SYNCCALL_FAIL, "synccall err", CommonTp::IntValueCallback);
    LVOS_TP_REG(SYNCCALL_CHANNEL_FAIL, "synccall channel err", CommonTp::IntValueCallback);
    LVOS_TP_REG(SYNCCALL_OPCODE_FAIL, "synccall opcode err", CommonTp::BoolValueCallback);
    LVOS_TP_REG(PUT_SLICE_ZERO_ALLOC_FAIL, "put slice zero alloc err", CommonTp::PointerValueCallback);
    LVOS_TP_REG(PUT_SLICE_NORMAL_ALLOC_FAIL, "put slice normal alloc err", CommonTp::PointerValueCallback);
    LVOS_TP_REG(WRITE_SLICE_NULL_FAIL, "write slice err", CommonTp::PointerValueCallback);
    LVOS_TP_REG(RCACHE_MANAGER_INIT_FAIL, "rcache manager init err", CommonTp::IntValueCallback);
    LVOS_TP_REG(CACHE_RECOVER_TYPE_FAIL, "cache recover type", CommonTp::IntValueCallback);
    LVOS_TP_REG(CACHE_RECOVER_TYPE_INNER_FAIL, "cache recover inner type", CommonTp::IntValueCallback);
    LVOS_TP_REG(NO_PROCESS_CACHE_RECOVER, "no process cache recover", CommonTp::NoProcessCallback);
    LVOS_TP_REG(WCACHE_ALLOC_FAIL, "wcache alloc err", CommonTp::PointerValueCallback);
    LVOS_TP_REG(WCACHE_INDEX_TABLE_FAIL, "wcache index table err", CommonTp::PointerValueCallback);
    LVOS_TP_REG(WCACHE_GET_OK, "wcache get ok", CommonTp::IntValueCallback);
    LVOS_TP_REG(WCACHE_NOT_EXIST, "wcache alloc err", CommonTp::IntValueCallback);
    LVOS_TP_REG(UNDERFS_INIT_FAIL, "under fs init err", CommonTp::IntValueCallback);
    LVOS_TP_REG(WCACHE_GET_META_SLICE_FAIL, "wcache get meta slice err", CommonTp::IntValueCallback);
    LVOS_TP_REG(UNDERFS_DELETE_ERR, "underfs delete err", CommonTp::IntValueCallback);
    LVOS_TP_REG(NO_PROCESS_WCACHE_EXPIRED_CLEAR, "no process wcache expired clear", CommonTp::NoProcessCallback);
    LVOS_TP_REG(RECOVER_CACHE_FLOWID_FAIL, "recover cache flowid err", CommonTp::IntValueCallback);
    LVOS_TP_REG(NO_PROCESS_UPGRADE_FLUSH, "no procesee upgrate flush", CommonTp::NoProcessCallback);
    LVOS_TP_REG(WCACHE_STATE_NOT_NORMAL, "wcache state not normal", CommonTp::BoolValueCallback);
    LVOS_TP_REG(RCACHE_EVICT_PARAM_FAIL, "rcache gc evict err", CommonTp::NoProcessCallback);
    LVOS_TP_REG(RCACHE_GC_PARAM_FAIL, "rcache gc param err", CommonTp::NoProcessCallback);
    LVOS_TP_REG(NO_PROCESS_RCACHE_EVICT, "no process rcache evict init", CommonTp::NoProcessCallback);
    LVOS_TP_REG(NO_PROCESS_RCACHE_GC, "no process rcache gc init", CommonTp::IntValueCallback);
    LVOS_TP_REG(MIRROR_FLOW_CREATE_WCACHE_FAIL, "mirror flow create wcache err", CommonTp::IntValueCallback);
    LVOS_TP_REG(NO_PROCESS_RCACHE_FIND, "no process rcache find", CommonTp::NoProcessCallback);
    LVOS_TP_REG(RCACHE_ALLOC_OBJ_FAIL, "rcache alloc obj err", CommonTp::PointerValueCallback);
    LVOS_TP_REG(RCACHE_INIT_OBJ_FAIL, "rcache init obj err", CommonTp::IntValueCallback);
    LVOS_TP_REG(NO_PROCESS_CACHE_PROCESS, "no process cache process", CommonTp::NoProcessCallback);
    LVOS_TP_REG(NO_PROCESS_CACHE_INIT, "no process cache init", CommonTp::NoProcessCallback);
    LVOS_TP_REG(NO_PROCESS_SERVER_START, "no process server start", CommonTp::NoProcessCallback);
    LVOS_TP_REG(NO_PROCESS_CONFIG, "no process config", CommonTp::NoProcessCallback);
    LVOS_TP_REG(NO_PROCESS_UNDERFS_INIT, "no process underfs init", CommonTp::NoProcessCallback);
    LVOS_TP_REG(NO_PROCESS_MIRROR_SERVER_INIT, "no process mirror server init", CommonTp::NoProcessCallback);
    LVOS_TP_REG(NO_PROCESS_MIRROR_SERVER_CRB_INIT, "no process mirror crb init", CommonTp::NoProcessCallback);
    LVOS_TP_REG(NO_PROCESS_EXECUTOR, "no process executor init", CommonTp::NoProcessCallback);
    LVOS_TP_REG(NO_PROCESS_ROLLBACK_SERVICE_INIT, "no process service init", CommonTp::NoProcessCallback);
    LVOS_TP_REG(NO_PROCESS_WCACHE_PUT, "no process wcache put", CommonTp::NoProcessCallback);
    LVOS_TP_REG(NO_PROCESS_WCACHE_MANAGER_EMPTY_EVICT, "no process wcache evict", CommonTp::NoProcessCallback);
    LVOS_TP_REG(WCACHE_HANDLE_BROCK_FLOWID_FAIL, "wcache handle brock flowid err", CommonTp::IntValueCallback);
    LVOS_TP_REG(HANDLE_CACHE_BROKE_OK, "handle cache broke ok", CommonTp::IntValueCallback);
    LVOS_TP_REG(NO_PROCESS_DESTROY_EVICT_THREAD, "no process destroy evict thread", CommonTp::NoProcessCallback);
    LVOS_TP_REG(NO_PROCESS_WCACHE_FLUSH, "no process wcache flush", CommonTp::NoProcessCallback);
    LVOS_TP_REG(WCACHE_HANDLE_BROCK_FLUSH, "wcache handle brock flush", CommonTp::BoolValueCallback);
    LVOS_TP_REG(NO_PROCESS_WCACHE_MANAGER_EXPIRED_CLEAR, "no process wcache expired clear", CommonTp::NoProcessCallback);
    LVOS_TP_REG(WCACHE_HANDLE_BROCK_EXPIRED_CLEAR, "wcache handle bock expired clear", CommonTp::BoolValueCallback);
    LVOS_TP_REG(WCACHE_STATE_NORMAL, "wcache state normal", CommonTp::BoolValueCallback);
    LVOS_TP_REG(HANDLE_PROC_BROKEN_FAIL, "handle proc broken fail", CommonTp::BoolValueCallback);
    LVOS_TP_REG(HANDLE_PROC_BROKE_OK, "handle proc broken ok", CommonTp::IntValueCallback);
    LVOS_TP_REG(WCACHE_HANDLE_PROC_BROCK_EXPIRED_CLEAR, "wcache proc broken expired clear", CommonTp::BoolValueCallback);
    LVOS_TP_REG(WCACHE_HANDLE_PROC_BROCK_ROLE_ERR, "wcache handle proc broke role err", CommonTp::IntValueCallback);
    LVOS_TP_REG(NO_PROCESS_CLEAR_PROC_CACHE, "no process clear proc cache", CommonTp::NoProcessCallback);
    LVOS_TP_REG(CACHE_DELETE_RCACHE_MANAGER_ERR, "cache delete rcache manager err", CommonTp::IntValueCallback);
    LVOS_TP_REG(MIRROR_SERVER_HDL_LOAD_FAIL, "mirror server handle load err", CommonTp::IntValueCallback);
    LVOS_TP_REG(MIRROR_SERVER_HDL_STAT_FAIL, "mirror server handle stat err", tp::CommonTp::IntValueCallback);
    LVOS_TP_REG(MIRROR_SERVER_HDL_LIST_FAIL, "mirror server handle list err", tp::CommonTp::IntValueCallback);
    LVOS_TP_REG(WCACHE_GET_MEM_SLICE_FAIL, "wcache get mem slice fail", tp::CommonTp::IntValueCallback);
    LVOS_TP_REG(WCACHE_GET_DISK_SLICE_FAIL, "wcache get disk slice fail", tp::CommonTp::IntValueCallback);
    LVOS_TP_REG(WCACHE_GET_EVICT_OFFSET_FAIL, "wcache get evict offset fail", tp::CommonTp::IntValueCallback);
    LVOS_TP_REG(WCACHE_CHECK_RCACHE_LEVEL_FAIL, "wcache check rcache level fail", tp::CommonTp::BoolValueCallback);
    LVOS_TP_REG(WCACHE_FLUSH_FAIL, "wcache flush fail", tp::CommonTp::IntValueCallback);
    LVOS_TP_REG(WCACHE_EXPIRE_FAIL, "wcache flush fail", tp::CommonTp::IntValueCallback);
    LVOS_TP_REG(RCACHE_GET_MEM_SLICE_FAIL, "rcache get mem slice fail", tp::CommonTp::IntValueCallback);
    LVOS_TP_REG(RCACHE_GET_EVICT_IO_FAIL, "rcache get evict io fail", tp::CommonTp::LongValueCallback);
    LVOS_TP_REG(RCACHE_GET_DISK_SLICE_FAIL, "rcache get disk slice fail", tp::CommonTp::IntValueCallback);
    LVOS_TP_REG(BDM_RW_IO_FAIL, "bdm io err", tp::CommonTp::NoProcessCallback);
    LVOS_TP_REG(BDM_ALLOC_BLOCK_FAIL, "bdm alloc block fail", tp::CommonTp::IntValueCallback);
    LVOS_TP_REG(WCACHE_PUT_FAIL, "wcache put fail", tp::CommonTp::IntValueCallback);
    LVOS_TP_REG(UNDERFS_CEPH_CREAT_FAIL, "ceph creat fail", tp::CommonTp::IntValueCallback);
    LVOS_TP_REG(UNDERFS_SET_BUILDER_NULL, "set hdfs builder null", CommonTp::PointerValueCallback);
    LVOS_TP_REG(UNDERFS_HDFS_CONNECT_FAIL, "hdfs connect fail", CommonTp::PointerValueCallback);
    LVOS_TP_REG(UNDERFS_CEPH_READ_FILE_FAIL, "ceph read file fail", tp::CommonTp::IntValueCallback);
    LVOS_TP_REG(UNDERFS_CEPH_CONNECT_FAIL, "ceph connect fail", tp::CommonTp::IntValueCallback);
    LVOS_TP_REG(UNDERFS_CEPH_IOCTX_CREAT_FAIL, "ceph ioctx creat fail", tp::CommonTp::IntValueCallback);
    LVOS_TP_REG(UNDERFS_CEPH_GET_FAIL, "ceph get object fail", tp::CommonTp::IntValueCallback);
    LVOS_TP_REG(UNDERFS_CEPH_DELETE_NOT_EXIST, "ceph delete not exist", tp::CommonTp::IntValueCallback);
    LVOS_TP_REG(UNDERFS_CEPH_STAT_NOT_EXIST, "ceph stat not exist", tp::CommonTp::IntValueCallback);
    LVOS_TP_REG(MIRROR_SERVER_GET_SLICE_FAIL, "mirror server get slice err", tp::CommonTp::IntValueCallback);
    LVOS_TP_REG(MIRROR_SERVER_HDL_PUT_FAIL, "mirror server handle put err", tp::CommonTp::IntValueCallback);
    LVOS_TP_REG(MIRROR_SERVER_HDL_GET_FAIL, "mirror server handle get err", tp::CommonTp::IntValueCallback);
    LVOS_TP_REG(MIRROR_SERVER_HDL_DELETE_FAIL, "mirror server handle delete err", tp::CommonTp::IntValueCallback);
    LVOS_TP_REG(NO_PROCESS_SLAVE_NEGOTIATE_NO_JUDGE_MASTER, "no process wcache judge master", CommonTp::NoProcessCallback);
    LVOS_TP_REG(NO_PROCESS_SLAVE_NEGOTIATE_NO_SEND, "no process wcache send negotiate", CommonTp::NoProcessCallback);
    LVOS_TP_REG(WCACHE_NEGOTIATE_FLAG_CLEAR, "wcache negotiate flag clear", CommonTp::BoolValueCallback);
    LVOS_TP_REG(NEGOTIATE_MASTER_FLAG, "wcache negotiate master flag true", CommonTp::BoolValueCallback);
    LVOS_TP_REG(WCACHE_NEGOTIATE_FLAG_TRUE, "wcache negotiate flag true", CommonTp::BoolValueCallback);
    LVOS_TP_REG(NO_PROCESS_MASTER_NEGOTIATE_NO_EVICT, "no process wcache evict ", CommonTp::NoProcessCallback);
}

void tp::CacheTp::Deregister() noexcept
{
    LVOS_TP_UNREG(CACHE_RECOVER_CACHE_FAIL);
    LVOS_TP_UNREG(SLICE_OPERATOR_4_FLOW_MEMORY);
    LVOS_TP_UNREG(LISTALL_REMOTE_OVER_1000);
    LVOS_TP_UNREG(LISTALL_REMOTE_RSP_OVER_LIMIT);
    LVOS_TP_UNREG(SLICE_COPY_DISK2MEMORY_OK);
    LVOS_TP_UNREG(SLICE_COPY_MEMORY2MEMORY_ERR);
    LVOS_TP_UNREG(SLICE_OPERATOR_FLOW_MEMORY);
    LVOS_TP_UNREG(SLICE_OPERATOR_2_FLOW_MEMORY);
    LVOS_TP_UNREG(CACHE_RECOVER_FM_GET_ALL_OBJECT_FAIL);
    LVOS_TP_UNREG(WCACHE_READ_CALLBACK_FAIL);
    LVOS_TP_UNREG(LOG_INIT_FAIL);
    LVOS_TP_UNREG(TRACE_FILE_OPPEN_FAIL);
    LVOS_TP_UNREG(EVICT_NEGOTIATE_VECTOR_EMPTY);
    LVOS_TP_UNREG(EVICT_NEGOTIATE_GET_MASTERNODE);
    LVOS_TP_UNREG(CONFIG_INIT_FAIL);
    LVOS_TP_UNREG(DESTROY_WCACHE_FAIL);
    LVOS_TP_UNREG(RCACHE_MANAGER_DELETE_ERR);
    LVOS_TP_UNREG(NO_PROCESS_CLEAR_OLD_CACHE);
    LVOS_TP_UNREG(NO_PROCESS_FLUSH);
    LVOS_TP_UNREG(LIST_LIST_FAIL);
    LVOS_TP_UNREG(LIST_MALLOC_RSP_FAIL);
    LVOS_TP_UNREG(PUT_ALLOC_SLICE_FAIL);
    LVOS_TP_UNREG(PUT_SLICELEN_ZERO_ALLOC_SLICE_FAIL);
    LVOS_TP_UNREG(WCACHE_FLOW_OFFSET_FAIL);
    LVOS_TP_UNREG(WCACHE_HOLD_WAIT_FAIL);
    LVOS_TP_UNREG(TRACE_CREATE_DIR_FAIL);
    LVOS_TP_UNREG(TRACE_PATH_REAL_FAIL);
    LVOS_TP_UNREG(UNDERFS_OPEN_DIR_FAIL);
    LVOS_TP_UNREG(UNDERFS_MKDIR_FAIL);
    LVOS_TP_UNREG(QUEUE_INIT_FAIL);
    LVOS_TP_UNREG(EXECUTOR_THREAD_FAIL);
    LVOS_TP_UNREG(RCACHE_GC_THREAD_FAIL);
    LVOS_TP_UNREG(RCACHE_EVICT_THREAD_FAIL);
    LVOS_TP_UNREG(CLI_AGENT_INIT_ERR);
    LVOS_TP_UNREG(CLI_SERVER_DIAGNOSE_HANDLER_ERR);
    LVOS_TP_UNREG(CLI_SERVER_DIAGNOSE_INIT_ERR);
    LVOS_TP_UNREG(WCACHE_FLOW_DISK_FAIL);
    LVOS_TP_UNREG(SYNCCALL_FAIL);
    LVOS_TP_UNREG(SYNCCALL_CHANNEL_FAIL);
    LVOS_TP_UNREG(SYNCCALL_OPCODE_FAIL);
    LVOS_TP_UNREG(PUT_SLICE_ZERO_ALLOC_FAIL);
    LVOS_TP_UNREG(PUT_SLICE_NORMAL_ALLOC_FAIL);
    LVOS_TP_UNREG(WRITE_SLICE_NULL_FAIL);
    LVOS_TP_UNREG(RCACHE_MANAGER_INIT_FAIL);
    LVOS_TP_UNREG(CACHE_RECOVER_TYPE_FAIL);
    LVOS_TP_UNREG(CACHE_RECOVER_TYPE_INNER_FAIL);
    LVOS_TP_UNREG(NO_PROCESS_CACHE_RECOVER);
    LVOS_TP_UNREG(WCACHE_ALLOC_FAIL);
    LVOS_TP_UNREG(WCACHE_INDEX_TABLE_FAIL);
    LVOS_TP_UNREG(WCACHE_GET_OK);
    LVOS_TP_UNREG(WCACHE_NOT_EXIST);
    LVOS_TP_UNREG(UNDERFS_INIT_FAIL);
    LVOS_TP_UNREG(WCACHE_DELETE_FLOWID_ERR);
    LVOS_TP_UNREG(WCACHE_PUT_FAIL);
    LVOS_TP_UNREG(RCACHE_MANAGER_DELETE_ERR);
    LVOS_TP_UNREG(WCACHE_GET_META_SLICE_FAIL);
    LVOS_TP_UNREG(UNDERFS_DELETE_ERR);
    LVOS_TP_UNREG(NO_PROCESS_WCACHE_EXPIRED_CLEAR);
    LVOS_TP_UNREG(RECOVER_CACHE_FLOWID_FAIL);
    LVOS_TP_UNREG(NO_PROCESS_UPGRADE_FLUSH);
    LVOS_TP_UNREG(WCACHE_STATE_NOT_NORMAL);
    LVOS_TP_UNREG(RCACHE_EVICT_PARAM_FAIL);
    LVOS_TP_UNREG(RCACHE_GC_PARAM_FAIL);
    LVOS_TP_UNREG(NO_PROCESS_RCACHE_EVICT);
    LVOS_TP_UNREG(NO_PROCESS_RCACHE_GC);
    LVOS_TP_UNREG(MIRROR_FLOW_CREATE_WCACHE_FAIL);
    LVOS_TP_UNREG(NO_PROCESS_RCACHE_FIND);
    LVOS_TP_UNREG(RCACHE_ALLOC_OBJ_FAIL);
    LVOS_TP_UNREG(RCACHE_INIT_OBJ_FAIL);
    LVOS_TP_UNREG(NO_PROCESS_CACHE_PROCESS);
    LVOS_TP_UNREG(NO_PROCESS_CACHE_INIT);
    LVOS_TP_UNREG(NO_PROCESS_SERVER_START);
    LVOS_TP_UNREG(NO_PROCESS_CONFIG);
    LVOS_TP_UNREG(NO_PROCESS_UNDERFS_INIT);
    LVOS_TP_UNREG(NO_PROCESS_MIRROR_SERVER_INIT);
    LVOS_TP_UNREG(NO_PROCESS_MIRROR_SERVER_CRB_INIT);
    LVOS_TP_UNREG(NO_PROCESS_EXECUTOR);
    LVOS_TP_UNREG(NO_PROCESS_ROLLBACK_SERVICE_INIT);
    LVOS_TP_UNREG(NO_PROCESS_WCACHE_PUT);
    LVOS_TP_UNREG(NO_PROCESS_WCACHE_MANAGER_EMPTY_EVICT);
    LVOS_TP_UNREG(WCACHE_HANDLE_BROCK_FLOWID_FAIL);
    LVOS_TP_UNREG(HANDLE_CACHE_BROKE_OK);
    LVOS_TP_UNREG(NO_PROCESS_DESTROY_EVICT_THREAD);
    LVOS_TP_UNREG(NO_PROCESS_WCACHE_FLUSH);
    LVOS_TP_UNREG(WCACHE_HANDLE_BROCK_FLUSH);
    LVOS_TP_UNREG(NO_PROCESS_WCACHE_MANAGER_EXPIRED_CLEAR);
    LVOS_TP_UNREG(WCACHE_HANDLE_BROCK_EXPIRED_CLEAR);
    LVOS_TP_UNREG(WCACHE_STATE_NORMAL);
    LVOS_TP_UNREG(HANDLE_PROC_BROKEN_FAIL);
    LVOS_TP_UNREG(HANDLE_PROC_BROKE_OK);
    LVOS_TP_UNREG(WCACHE_HANDLE_PROC_BROCK_EXPIRED_CLEAR);
    LVOS_TP_UNREG(WCACHE_HANDLE_PROC_BROCK_ROLE_ERR);
    LVOS_TP_UNREG(NO_PROCESS_CLEAR_PROC_CACHE);
    LVOS_TP_UNREG(CACHE_DELETE_RCACHE_MANAGER_ERR);
    LVOS_TP_UNREG(MIRROR_SERVER_HDL_LOAD_FAIL);
    LVOS_TP_UNREG(MIRROR_SERVER_HDL_STAT_FAIL);
    LVOS_TP_UNREG(MIRROR_SERVER_HDL_LIST_FAIL);
    LVOS_TP_UNREG(WCACHE_GET_MEM_SLICE_FAIL);
    LVOS_TP_UNREG(WCACHE_GET_DISK_SLICE_FAIL);
    LVOS_TP_UNREG(WCACHE_GET_EVICT_OFFSET_FAIL);
    LVOS_TP_UNREG(WCACHE_CHECK_RCACHE_LEVEL_FAIL);
    LVOS_TP_UNREG(WCACHE_FLUSH_FAIL);
    LVOS_TP_UNREG(WCACHE_EXPIRE_FAIL);
    LVOS_TP_UNREG(RCACHE_GET_MEM_SLICE_FAIL);
    LVOS_TP_UNREG(RCACHE_GET_EVICT_IO_FAIL);
    LVOS_TP_UNREG(RCACHE_GET_DISK_SLICE_FAIL);
    LVOS_TP_UNREG(BDM_RW_IO_FAIL);
    LVOS_TP_UNREG(BDM_ALLOC_BLOCK_FAIL);
    LVOS_TP_UNREG(UNDERFS_CEPH_CREAT_FAIL);
    LVOS_TP_UNREG(UNDERFS_SET_BUILDER_NULL);
    LVOS_TP_UNREG(UNDERFS_CEPH_READ_FILE_FAIL);
    LVOS_TP_UNREG(UNDERFS_CEPH_CONNECT_FAIL);
    LVOS_TP_UNREG(UNDERFS_CEPH_IOCTX_CREAT_FAIL);
    LVOS_TP_UNREG(UNDERFS_CEPH_GET_FAIL);
    LVOS_TP_UNREG(UNDERFS_CEPH_DELETE_NOT_EXIST);
    LVOS_TP_UNREG(UNDERFS_CEPH_STAT_NOT_EXIST);
    LVOS_TP_UNREG(UNDERFS_HDFS_CONNECT_FAIL);
    LVOS_TP_UNREG(MIRROR_SERVER_GET_SLICE_FAIL);
    LVOS_TP_UNREG(MIRROR_SERVER_HDL_PUT_FAIL);
    LVOS_TP_UNREG(MIRROR_SERVER_HDL_GET_FAIL);
    LVOS_TP_UNREG(MIRROR_SERVER_HDL_DELETE_FAIL);
    LVOS_TP_UNREG(NO_PROCESS_SLAVE_NEGOTIATE_NO_JUDGE_MASTER);
    LVOS_TP_UNREG(NO_PROCESS_SLAVE_NEGOTIATE_NO_SEND);
    LVOS_TP_UNREG(WCACHE_NEGOTIATE_FLAG_CLEAR);
    LVOS_TP_UNREG(NEGOTIATE_MASTER_FLAG);
    LVOS_TP_UNREG(WCACHE_NEGOTIATE_FLAG_TRUE);
    LVOS_TP_UNREG(NO_PROCESS_MASTER_NEGOTIATE_NO_EVICT);
}
#else
void tp::CacheTp::Register() noexcept {}

void tp::CacheTp::Deregister() noexcept {}
#endif
