#configuration for boostio
[bio]

bio.log.level = info

## cluster manager related setting
# desired pt count in this group, max value is 8192
bio.cm.pts_count = 16
# timeout for other nodes registered to group master
bio.cm.register_timeout_sec = 30
# perm fault timeout for other nodes registered to group master
bio.cm.register_perm_timeout_sec = 60
# register to zk host, suggest configure multi zk server hosts, must configure correct zk host
bio.cm.zk_host =

## network related setting
bio.net.data.ip_mask = 127.0.0.1/24
bio.net.data.listen_port = 7201
bio.net.data.protocol = tcp
# only RDMA support busy polling
bio.net.rpc.data.busy_polling_mode = false
bio.net.rpc.data.workers_count = 4
bio.net.ipc.data.busy_polling_mode = false
bio.net.ipc.data.workers_count = 4
bio.net.request.executor.thread.num = 8
bio.net.request.executor.queue.size = 1024

## memory or disk manager related setting
bio.segment.size_in_mb = 4
bio.mem.size_in_gb = 50
bio.disk.path = /dev/sdxx:/dev/sdyy
bio.rcache.evict_water_level = 90
bio.cache.mem_read_write_ratio = 5:5
bio.cache.disk_read_write_ratio = 5:5

## underfs related setting
bio.underfs.ceph.cfg.path = /etc/ceph/ceph.conf
bio.underfs.ceph.cluster = ceph
bio.underfs.ceph.user = client.admin
# current version only support 1 pools
bio.underfs.ceph.pool = 0:jfspool0,1:jfspool1
