#configuration for boostio
[bio]

bio.log.level = info

## cluster manager related setting
# if the node is group master or candidate
bio.cmm.enabled = true
# desired initial node count in this group, max value is 256
bio.cmc.initial.nodes_count = 2
# desired node count in this group, max value is 256
bio.cmc.nodes_count = 2
# desired pt count in this group, max value is 8192
bio.cmc.pts_count = 16
# timeout for other nodes registered to group master
bio.cmc.register_timeout_sec = 120

# zk host ip and ip mask
bio.zk_host.ip = 127.0.0.1/24
bio.zk_host.port = 2181

## network related setting
bio.net.data.protocol = tcp
# only RDMA support busy polling
bio.net.data.busy_polling_mode = false
bio.net.data.ctrl_workers_count = 4
bio.net.data.data_workers_count = 2
bio.net.data.ip_mask = 127.0.0.1/24
bio.net.data.listen_port = 9898
# group master ip and ip mask
bio.net.cmm.ip_mask = 127.0.0.1/24
bio.net.cmm.listen_port = 9899

## multiple group related configuration
# group id of bio in big cluster
bio.group.id = 0

## memory or disk manager related setting
bio.segment.size_in_mb = 2
bio.mem.size_in_gb = 8
bio.disk.size_in_gb = 8
bio.disk.path = /dev/sdxx:/dev/sdyy

## file system media/capacity/buffer related setting
bio.client.buffer.size_in_mb = 512

## security related setting
bio.security.enabled = false
bio.security.conf = bio_security.conf
