# configuration for boostio
[bio]
## Log
bio.log.level = debug

## Network
bio.net.data.ip_mask = 127.0.0.1/24
bio.net.data.listen_port = 7201
bio.net.data.protocol = tcp
bio.net.rpc.data.busy_polling_mode = false
bio.net.rpc.data.workers_count = 4
bio.net.ipc.data.busy_polling_mode = false
bio.net.ipc.data.workers_count = 4
bio.net.request.executor.thread.num = 8
bio.net.request.executor.queue.size = 1024
bio.net.tls.enable.switch = true
bio.net.tls.ca.cert.path = /path/CA/cacert.pem
bio.net.tls.ca.crl.path =
bio.net.tls.server.cert.path = /path/server/servercert.pem
bio.net.tls.server.key.path = /path/server/serverkey.pem
bio.net.tls.server.key.pass.path = /path/server/server.keypass
bio.net.hesc.server.tls.kfs.master.path = /path/server/master/kfsa
bio.net.hesc.server.tls.kfs.pass.standby.path = /path/server/standby/kfsb

## Cluster manager
bio.cm.initial.nodes_count = 2
bio.cm.pts_count = 16
bio.cm.register_timeout_sec = 30
bio.cm.register_perm_timeout_sec = 60
bio.cm.zk_host =

## Cache
bio.segment.size_in_mb = 4
bio.mem.size_in_gb = 50
bio.disk.path = /dev/sdxx:/dev/sdyy
bio.rcache.evict_water_level = 90
bio.cache.mem_read_write_ratio = 5:5
bio.cache.disk_read_write_ratio = 5:5

## Underfs
bio.underfs.ceph.cfg.path = /etc/ceph/ceph.conf
bio.underfs.ceph.cluster = ceph
bio.underfs.ceph.user = client.admin
bio.underfs.ceph.pool = 0:jfspool0,1:jfspool1