/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2023-2023. All rights reserved.
 */

#ifndef BIO_TRACE_H
#define BIO_TRACE_H

#include "htracer.h"

namespace ock {
namespace bio {
constexpr int32_t SERVICE_ID  = 0;

enum SdkTracerType {
    SDK_TRACE_START = htracer::GetTraceId(SERVICE_ID, 0),
    SDK_TRACE_CREATE_CACHE,
    SDK_TRACE_DESTROY_CACHE,
    SDK_TRACE_PUT,
    SDK_TRACE_PUT_GET_PT,
    SDK_TRACE_PUT_ALLOC_OFF,
    SDK_TRACE_PUT_SEND,
    SDK_TRACE_PUT_PREPARE_GET_SLICE,
    SDK_TRACE_PUT_PREPARE_COPY_DATA,
    SDK_TRACE_PUT_PREPARE_SLICE_SERIALIZATION,
    SDK_TRACE_PUT_PREPARE,
    SDK_TRACE_GET,
    SDK_TRACE_GET_SEND,
    SDK_TRACE_GET_LOCAL,
    SDK_TRACE_GET_REMOTE,
    SDK_TRACE_GET_COPY2U,
    SDK_TRACE_DELETE,
    SDK_TRACE_LOAD,
    SDK_TRACE_LISTALL,
    SDK_TRACE_STAT,

    SDK_TRACE_W_S_1_4K,
    SDK_TRACE_W_S_4_8K,
    SDK_TRACE_W_S_8_64K,
    SDK_TRACE_W_S_64_128K,
    SDK_TRACE_W_S_128_256K,
    SDK_TRACE_W_S_256K_1M,
    SDK_TRACE_W_S_1_2M,
    SDK_TRACE_W_S_2_4M,
    SDK_TRACE_W_S_4M,
    SDK_TRACE_R_S_1_4K,
    SDK_TRACE_R_S_4_8K,
    SDK_TRACE_R_S_8_64K,
    SDK_TRACE_R_S_64_128K,
    SDK_TRACE_R_S_128_256K,
    SDK_TRACE_R_S_256K_1M,
    SDK_TRACE_R_S_1_2M,
    SDK_TRACE_R_S_2_4M,
    SDK_TRACE_R_S_4M,
    SDK_TRACE_END,
};

enum MirrorTracerType {
    MIRROR_TRACE_START = SDK_TRACE_END,
    MIRROR_TRACE_PUT_HDL,
    MIRROR_TRACE_PUT_READ_DATA,
    MIRROR_TRACE_PUT,
    MIRROR_TRACE_GET_HDL,
    MIRROR_TRACE_GET_WRITE_DATA,
    MIRROR_TRACE_GET_COPY_DATA,
    MIRROR_TRACE_GET,
    MIRROR_TRACE_DEL_HDL,
    MIRROR_TRACE_DEL,
    MIRROR_TRACE_STAT_HDL,
    MIRROR_TRACE_STAT,
    MIRROR_TRACE_LOAD_HDL,
    MIRROR_TRACE_LOAD,
    MIRROR_TRACE_QUERYPTVIEW_HDL,
    MIRROR_TRACE_CREATEFLOW_HDL,
    MIRROR_TRACE_END,
};

enum WcacheTracerType {
    WCACHE_TRACE_START = MIRROR_TRACE_END,
    WCACHE_TRACE_ALLOC_ID,
    WCACHE_TRACE_CREATE_OBJ,
    WCACHE_TRACE_DESTROY_OBJ,
    WCACHE_TRACE_GET_SLICE,
    WCACHE_TRACE_PUT,
    WCACHE_TRACE_GET,
    WCACHE_TRACE_DEL,
    WCACHE_TRACE_STAT,
    WCACHE_TRACE_EVICT2DISK,
    WCACHE_TRACE_EVICT2UNDERFS,
    WCACHE_TRACE_PUT_RCACHE,
    WCACHE_TRACE_END,
};

enum RcacheTracerType {
    RCACHE_TRACE_START = WCACHE_TRACE_END,
    RCACHE_TRACE_CREATE_OBJ,
    RCACHE_TRACE_DESTROY_OBJ,
    RCACHE_TRACE_GET_SLICE,
    RCACHE_TRACE_PUT,
    RCACHE_TRACE_GET,
    RCACHE_TRACE_DEL,
    RCACHE_TRACE_LOAD,
    RCACHE_TRACE_STAT,
    RCACHE_TRACE_EVICT2DISK,
    RCACHE_TRACE_EVICT2NULL,
    RCACHE_TRACE_END,
};

enum FlowTracerType {
    FLOW_TRACE_START = RCACHE_TRACE_END,
    FLOW_TRACE_CREATE_OBJ,
    FLOW_TRACE_DESTROY_OBJ,
    FLOW_TRACE_GETALL_OBJ,
    FLOW_TRACE_PRELOAD_OBJ,
    FLOW_TRACE_GETADDR,
    FLOW_TRACE_TRUNCATE,
    FLOW_TRACE_HOLDWAIT,
    FLOW_TRACE_SEAL,
    FLOW_TRACE_END,
};

enum BdmTracerType {
    BDM_TRACE_START = FLOW_TRACE_END,
    BDM_TRACE_SEG_ALLOC,
    BDM_TRACE_SEG_FREE,
    BDM_TRACE_WRITE_SYNC,
    BDM_TRACE_READ_SYNC,
    BDM_TRACE_WRITE_ASYNC,
    BDM_TRACE_READ_ASYNC,
    BDM_TRACE_END,
};

enum MemTracerType {
    MEM_TRACE_START = BDM_TRACE_END,
    MEM_TRACE_SEG_ALLOC,
    MEM_TRACE_SEG_FREE,
    MEM_TRACE_END,
};

enum UfsTracerType {
    UFS_TRACE_START = MEM_TRACE_END,
    UFS_TRACE_PUT,
    UFS_TRACE_GET,
    UFS_TRACE_DEL,
    UFS_TRACE_STAT,
    UFS_TRACE_END,
};

enum NetTracerType {
    NET_TRACE_START = UFS_TRACE_END,
    NET_TRACE_END,
};

enum CmTracerType {
    CM_TRACE_START = NET_TRACE_END,
    CM_TRACE_NOTIFY_NODEVIEW,
    CM_TRACE_NOTIFY_PTVIEW,
    CM_TRACE_END,
};

#define BIO_TRACE_START(TP_ID) TRACE_DELAY_BEGIN(TP_ID)
#define BIO_TRACE_END(TP_ID, RET_CODE) TRACE_DELAY_END(TP_ID, RET_CODE)
}
}
#endif // BIO_TRACE_H
