version: '2.0'
params:
  - name: BUILD_TYPE
    value: Debug
  - name: env_types
    value: image
envs:
  - condition: env_types == 'label'
    label: '${env_type}'
  - condition: env_types == 'image'
    resource:
      type: docker
      image: '${env_type}'
      mode: toolbox
      class: 16U32G
steps:
  PRE_BUILD:
    - checkout:
        path: boostio
    - codehub:
        url: https://szv-y.codehub.huawei.com/ComputingFoundationSoftware/ock-platform/hcom.git
        branch: master
        path: boostio/3rdparty/hcom/hcom
    - codehub:
        url: https://codehub-dg-y.huawei.com/hwsecurec_group/huawei_secure_c.git
        tag: tag_Huawei_Secure_C_V100R001C01SPC011B003_00001
        path: boostio/3rdparty/hcom/hcom/3rdparty/secure_c/huawei_secure_c
    - gitlab:
        url: https://szv-open.codehub.huawei.com/OpenSourceCenter/linux-rdma/rdma-core.git
        tag: v42.0
        path: boostio/3rdparty/hcom/hcom/3rdparty/rdma_core/rdma-core
    - codehub:
        url: https://szv-open.codehub.huawei.com/OpenSourceCenter/gabime/spdlog.git
        tag: v1.9.2
        path: boostio/3rdparty/spdlog/spdlog
    - gitlab:
        url: https://codehub-dg-y.huawei.com/hwsecurec_group/huawei_secure_c.git
        tag: tag_Huawei_Secure_C_V100R001C01SPC011B003_00001
        path: boostio/3rdparty/secure/huawei_secure_c
    - gitlab:
        url: https://szv-open.codehub.huawei.com/OpenSourceCenter/google/googletest.git
        tag: release-1.8.1
        path: boostio/3rdparty/gtest/gtest
    - gitlab:
        url: https://szv-open.codehub.huawei.com/OpenSourceCenter/apache/zookeeper.git
        tag: 3.8.1-h1
        path: boostio/3rdparty/zookeeper/zookeeper
    - gitlab:
        url: https://codehub-dg-y.huawei.com/OpenSourceCenter/sinojelly/mockcpp.git
        tag: v2.7
        path: boostio/test/llt/3rdparty/mockcpp
  BUILD:
    - build_execute:
        command: sh boostio/build.sh ${BUILD_TYPE}
        check:
          fail_on_error: true
          mode: sync
          buildcheck:
            project_dir: ${WORKSPACE}/boostio/
            exclude_dir: ${WORKSPACE}/boostio/output;${WORKSPACE}/boostio/test;${WORKSPACE}/boostio/3rdparty
        callstack: true