#Log, 0 stdout, 1 file, 2 stderr
bio.log.type = 1
bio.sdk.log.path = /var/log/boostio
#Security
bio.net.tls.enable.switch = true
bio.net.tls.ca.cert.path = /path/CA/cacert.pem
bio.net.tls.ca.crl.path =
bio.net.tls.client.cert.path = /path/client/clientcert.pem
bio.net.tls.client.key.path = /path/client/clientkey.pem
bio.net.tls.client.key.pass.path = /path/client/client.keypass
bio.net.hesc.client.tls.kfs.master.path = /path/client/master/kfsa
bio.net.hesc.client.tls.kfs.pass.standby.path = /path/client/standby/kfsb