# BoostIO 配置
[ubsio]

# 设置磁盘或分区路径。不填表示不使用磁盘设备，仅使用DRAM内存作为L2.5层。填写方式见配置说明。
ubsio.disk.path =

# ubsio单个进程内存占用，单位GB。保持性能情况下最小10GB。
ubsio.mem.size_in_gb = 150

# 一次VLLM启动中，管理内存的memcache local_server进程数量。例如A3分离模式固定填1，其他情况均填写VLLM进程数量。
ubsio.standalone.device_count = 0

# ubsio内存淘汰水位，取值范围0-100，无ubsio.disk.path配置时设置为90，有磁盘路径配置且希望UBSIO最小化内存占用时可设置为0。
ubsio.wcache.evict_water_level = 0
# ubsio磁盘淘汰水位，示例为90%
ubsio.wcache.disk_evict_water_level = 90
# 是否启动时初始化成新盘，如果初始化成新盘，最初一些请求可能因丢失kvcache数据导致推理引擎重算，性能降低。
ubsio.standalone.force_new_disk = false
# 设置日志输出级别。可选`error`、`warn`、`info`、`debug`、`trace`。
ubsio.log.level = info

# 以下配置无需修改
ubsio.bdm.io_engine = sync