# configuration for boostio
[ubsio]
## Log
ubsio.log.level = debug

## Network
ubsio.net.data.ip_mask = 127.0.0.1/24
ubsio.net.data.listen_port = 7201
ubsio.net.data.protocol = tcp
ubsio.net.rpc.data.busy_polling_mode = false
ubsio.net.rpc.data.workers_count = 4
ubsio.net.ipc.data.busy_polling_mode = false
ubsio.net.ipc.data.workers_count = 4
ubsio.net.request.executor.thread.num = 8
ubsio.net.request.executor.queue.size = 1024
ubsio.net.tls.enable.switch = true
ubsio.net.tls.ca.cert.path = /path/CA/cacert.pem
ubsio.net.tls.ca.crl.path =
ubsio.net.tls.server.cert.path = /path/server/servercert.pem
ubsio.net.tls.server.key.path = /path/server/serverkey.pem
ubsio.net.tls.server.key.pass.path =
ubsio.net.tls.server.decrypter.lib.path =
ubsio.net.tls.server.ssl.lib.dir =

## Cluster manager
ubsio.cm.initial.nodes_count = 2
ubsio.cm.copy_num = 2
ubsio.cm.pts_count = 16
ubsio.cm.register_timeout_sec = 20
ubsio.cm.register_perm_timeout_sec = 60
ubsio.cm.zk_host =

## Cache
ubsio.trace.enable = true
ubsio.wcache.negotiate.delay = 100
ubsio.cache.qos.enable = true
ubsio.data.crc.enable = false
ubsio.segment.size_in_mb = 4
ubsio.mem.size_in_gb = 50
ubsio.sdkmem.size_in_mb = 5120
ubsio.disk.path = /dev/sdxx:/dev/sdyy
ubsio.standalone.device_count = 0
ubsio.rcache.evict_water_level = 90
ubsio.cache.mem_read_write_ratio = 5:5
ubsio.cache.disk_read_write_ratio = 5:5

## Underfs
ubsio.underfs.file_system_type = ceph
ubsio.underfs.ceph.cfg.path = /etc/ceph/ceph.conf
ubsio.underfs.ceph.cluster = ceph
ubsio.underfs.ceph.user = client.admin
ubsio.underfs.ceph.pool = 0:jfspool0,1:jfspool1
