#Log, 0 stdout, 1 file, 2 stderr
ubsio.log.type = 1
ubsio.sdk.log.path = /var/log/ubsio
#Security
ubsio.net.tls.enable.switch = true
ubsio.net.tls.ca.cert.path = /path/CA/cacert.pem
ubsio.net.tls.ca.crl.path =
ubsio.net.tls.client.cert.path = /path/client/clientcert.pem
ubsio.net.tls.client.key.path = /path/client/clientkey.pem
ubsio.net.tls.client.key.pass.path =
ubsio.net.tls.client.decrypter.lib.path =